project:
  type: website

website:
  title: "Higher-Order Hackathon @Netsci 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - program.qmd
      - register.qmd
      - organizers.qmd

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true



