project:
  type: website

website:
  title: "A Blue Start at Netsci 2026"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - program.qmd
      - apply.qmd
      - organizers.qmd
      - coc.qmd

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true



